openapi: 3.1.0
info:
  version: 1.0.0
  title: nodejs-hw
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Training of developing JS backend
tags:
  - name: Contacts
    desciption: Operation with contacts
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/api/contacts/{id}/get.yaml'
  /contacts:
    post:
      $ref: '../swagger/paths/api/contacts/post.yaml'
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
