openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Training of developing JS backend
tags:
  - name: Contacts
    description: Operations with contacts
  - name: Auth
    description: Authentication operations
servers:
  - url: http://localhost:3000
paths:
  /api/contacts:
    get:
      $ref: '../swagger/paths/api/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/api/contacts/post.yaml'
  /api/contacts/{contactId}:
    get:
      $ref: '../swagger/paths/api/contacts/{contactId}/get.yaml'
    delete:
      $ref: '../swagger/paths/api/contacts/{contactId}/delete.yaml'
    patch:
      $ref: '../swagger/paths/api/contacts/{contactId}/patch.yaml'
  /api/auth/register:
    post:
      $ref: '../swagger/paths/api/auth/register.yaml'
  /api/auth/login:
    post:
      $ref: '../swagger/paths/api/auth/login.yaml'
  /api/auth/send-reset-email:
    post:
      $ref: '../swagger/paths/api/auth/send-reset-email.yaml'
  /api/auth/reset-pwd:
    post:
      $ref: '../swagger/paths/api/auth/reset-pwd.yaml'
  /api/auth/refresh:
    post:
      $ref: '../swagger/paths/api/auth/refresh.yaml'
  /api/auth/logout:
    post:
      $ref: '../swagger/paths/api/auth/logout.yaml'
  /api/auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/api/auth/get-oauth-url.yaml'
  /api/auth/confirm-oauth:
    post:
      $ref: '../swagger/paths/api/auth/confirm-oauth.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    contact:
      $ref: '../swagger/components/schemas/contact.yaml'
    user:
      $ref: '../swagger/components/schemas/user.yaml'
  responses:
    '401':
      $ref: '../swagger/components/responses/401.yaml'
    '500':
      $ref: '../swagger/components/responses/500.yaml'
