openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Training of developing JS backend
tags:
  - name: Contacts
    description: Operations with contacts
  - name: Auth
    description: Authentication operations
servers:
  - url: http://localhost:3000
  - url: https://hw2-mongodb-qxg7.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/auth/get-oauth-url.yaml'
  /auth/confirm-oauth:
    post:
      $ref: '../swagger/paths/auth/confirm-oauth.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    contact:
      $ref: '../swagger/components/schemas/contact.yaml'
    user:
      $ref: '../swagger/components/schemas/user.yaml'
  responses:
    '401':
      $ref: '../swagger/components/responses/401.yaml'
    '500':
      $ref: '../swagger/components/responses/500.yaml'
